### ISSUE TITLE
missing "grizzly_navigation/launch/control.launch" 

### ISSUE THREAD

**Issue by michael-mortimer** [g/grizzly_simulator#6]
missing "$(find grizzly_navigation)/launch/control.launch"  
called in
"$(find grizzly_gazebo)/launch/grizzly.launch"

**Comment by mikaelarguedas** [comment]
I assume you worked around it but I just faced the same issue so I'm commenting here.
Indeed this file has been renamed to `localization.launch` it is fixed upstream since https://github.com/g/grizzly_simulator/commit/fa1dc949c158185e5680aeb0e5482d07c8b8894f but hasn't been released since.
A more general question: Is a new release to be expected? Is there a plan to release the grizzly stack for newer rosdistros (jade/kinetic) in the future?

**Comment by gavanderhoorn** [comment]
Still an issue: [missing control.launch file](http://answers.ros.org/question/250869) on ROS Answers.
